#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCD54FCE3D964BEFB (paul@ganssle.io)
#
Name     : python-dateutil-legacypython
Version  : 2.6.1
Release  : 43
URL      : https://github.com/dateutil/dateutil/releases/download/2.6.1/python-dateutil-2.6.1.tar.gz
Source0  : https://github.com/dateutil/dateutil/releases/download/2.6.1/python-dateutil-2.6.1.tar.gz
Source99 : https://github.com/dateutil/dateutil/releases/download/2.6.1/python-dateutil-2.6.1.tar.gz.asc
Summary  : Extensions to the standard Python datetime module
Group    : Development/Tools
License  : BSD-3-Clause
Requires: python-dateutil-legacypython-license
Requires: python-dateutil-legacypython-python
Requires: python-dateutil-legacypython-legacypython
Requires: six
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : python-dateutil-legacypython-legacypython
BuildRequires : setuptools-legacypython
BuildRequires : setuptools-python
BuildRequires : six
BuildRequires : tzdata

%description
The dateutil module provides powerful extensions to the
        datetime module available in the Python standard library.

%package legacypython
Summary: legacypython components for the python-dateutil-legacypython package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the python-dateutil-legacypython package.


%package license
Summary: license components for the python-dateutil-legacypython package.
Group: Default

%description license
license components for the python-dateutil-legacypython package.


%package python
Summary: python components for the python-dateutil-legacypython package.
Group: Default

%description python
python components for the python-dateutil-legacypython package.


%prep
%setup -q -n python-dateutil-2.6.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537970360
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/python-dateutil-legacypython
cp LICENSE %{buildroot}/usr/share/doc/python-dateutil-legacypython/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/doc/python-dateutil-legacypython/LICENSE

%files python
%defattr(-,root,root,-)
